### ISSUE TITLE
Includes in pug with brunch.

### ISSUE THREAD

**Issue by Shugar** [bmatcuk/pug-brunch-static#1]
Hey man! I have a little problem with includes.

![image](https://cloud.githubusercontent.com/assets/5647725/18412407/5c1619b0-7796-11e6-836e-de7d0ff8751e.png)
![image](https://cloud.githubusercontent.com/assets/5647725/18412409/6990d7a6-7796-11e6-8808-4514b645508f.png)
![image](https://cloud.githubusercontent.com/assets/5647725/18412414/7cad9428-7796-11e6-8ee1-4ae6cc0a3b20.png)
Can you help me with it?

**Comment by bmatcuk** [comment]
I've just published v2.0.1. It should correct this issue =)
