### ISSUE TITLE
Brunch still including pug files as require modules

### ISSUE THREAD

**Issue by bigsweater** [bmatcuk/pug-brunch-static#2]
Forgive me if this is a brunch-static or html-brunch-static issue.

My files look like this:

```
app
  index.static.pug
  partials
    head.static.pug
    header.static.pug
```

Brunch is compiling the file appropriately to `index.html` in `public`, but I'm still seeing (empty) calls to `require` in my compiled `app.js` file:

```[javascript]
;require.register("partials/head.static.pug", function(exports, require, module) {

});

;require.register("partials/header.static.pug", function(exports, require, module) {

});
```

My `config.plugins.static` is pretty basic:

```[javascript]
    static: {
      processors: [
        require('html-brunch-static')({
          processors: [
            require('pug-brunch-static')({
              compileDebug: true
            })
          ]
        })
      ]
    },
```

Why is brunch still behaving as though the partials are actually JS modules?

**Comment by bmatcuk** [comment]
Unfortunately, this is a limitation in the way brunch works. [brunch-static](/bmatcuk/brunch-static) is kind of a hack to get static files to compile nicely inside brunch. Brunch assumes all plugins will output either javascript or CSS. For brunch-static, I chose to behave like a javascript plugin because it caused fewer issues. Even though it outputs "nothing" (since it writes output directly to static files), brunch adds that "nothing" to the end of the javascript file and wraps it up in the commonjs stuff =(

**Comment by bigsweater** [comment]
Thanks for your response. After (spending far too long) researching the issue, I figured that's what was up.

I was also having a separate issue where includes were not triggering a compile, but I have since switched to the official `jade-brunch` plugin, and I won't have time to help you test/debug for awhile. 

FWIW, jade-brunch compiles static templates fine, using their new(ish) static API, without extraneous `require` calls. It even refreshes when you change a partial, which is nice. (See some minor details about the setup [on my SO answer](http://stackoverflow.com/questions/34232007/how-to-render-jade-templates-into-html-using-brunch/40661418#40661418).) As long as templates are in `assets`, it works well. 

I wish it worked with Pug, but I'm guessing they're waiting for Pug to stabilize.

**Comment by vdcrea** [comment]
To avoid brunch to compile anything but js, just specify it in the brunch-config:

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'js/vendor.js': /^(?!app\/)/,
        'js/main.js': /^(app\/.*\.js)/ // target only real .js files
      }
    }
  }
}
```
