### ISSUE TITLE
Allow locals

### ISSUE THREAD

**Issue by stgogm** [bmatcuk/pug-brunch-static#4]
This would be a great addition since one of the main reasons to use Pug is the ability to use locals to assign dynamic values to the templates.

This plugin uses `compile` so the locals object should be passed in the options and then passed to the template function: https://pugjs.org/api/reference.html#pugcompilesource-options

**Comment by bmatcuk** [comment]
Hey @stgogm! Sorry it's taken me a while to get back to you! This sounds like a great addition! I just finished adding it =)

You'll need to grab the latest version of html-brunch-static (v1.4.0) and the latest version of pug-brunch-static (v3.0.0), both of which I just published to npm. The [context](https://github.com/bmatcuk/html-brunch-static#context-layouts-and-partials) will be exposed as local variables in your pug files. You can set the `defaultContext` in your bunch config, or set some variables in the front matter of your file. If you use pug for partials, they'll inherit the context from the referring file, and context will bubble up to layouts if you use pug for layouts.

Let me know if you run into any issues!
